### ISSUE TITLE
Error using new ggplot2 dev version and ggstance

### ISSUE THREAD

**Issue by seth-1** [lionel-/ggstance#11]
Hi!

I just updated ggplot2 to the newest github version and GeomBarh doesn't work anymore. I already tried reinstalling ggplot2 but that doesn't solve the problem.

> Error: GeomBarh was built with an incompatible version of ggproto.
> Please reinstall the package that provides this extension.

I am using:
"R version 3.3.1 (2016-06-21)"
ggstance_0.2.9000  ggplot2_2.1.0.9001

**Comment by lionel-** [comment]
hello, ggstance will be updated to the new ggplot2 either this week or the next.

**Comment by lionel-** [comment]
Soon on its way to CRAN.

**Comment by seth-1** [comment]
Thank you!
