### ISSUE TITLE
Modify bars in `geom_pointrangeh`

### ISSUE THREAD

**Issue by sammo3182** [lionel-/ggstance#15]
Thank you for the great package! The functions are very useful, especially the `geom_pointrangeh`, for my data visualization tasks. A question about it, though: how can I modify the interval bars (such as increasing the width or changing the color)? I saw you defined the arguments of the points and bars together with the `panel_scale` argument in the function. But is there any way I can define the parameters of the bars independently?

**Comment by lionel-** [comment]
Hi, it seems like that question would be better suited for stackoverflow or Community. It doesn't seem specific to ggstance but relevant for ggplot2 as well.
