### ISSUE TITLE
Order of items in legend

### ISSUE THREAD

**Issue by krlmlr** [lionel-/ggstance#21]
conflicts with order in which geoms are put by `position_dodgev()`.

In the plot I would expect the fill color to go from red to green to blue in the plot, corresponding to the legend.

``` r
library(tidyverse)
library(ggstance)
#> 
#> Attaching package: 'ggstance'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     geom_errorbarh, GeomErrorbarh

mpg %>% 
  ggplot(aes(x = cty, y = class, fill = drv)) +
  geom_boxploth()
```

![](https://i.imgur.com/LNMaZwc.png)

> Created on 2018-05-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lionel-** [comment]
This looks to be the same as in ggplot2 so this would have to be fixed upstream first. Can you file there please?

**Comment by krlmlr** [comment]
I think the problem is unique to _ggstance_.

In the original (vertical) plot, the colors go from left to right, and correspond to the legend order from top to bottom. This is expected. With _ggstance_, left becomes bottom and right becomes top, and the colors go from bottom to top while the legend remains unchanged. Also, the labels on the y-axis are in reverse alphabetical order, it seems more natural to have the alphabetical order running from top to bottom in this kind of plot.

Perhaps we just need `geom_boxplothr()` and friends (for r = reverse)? Or `stat_rev()`?

``` r
library(tidyverse)

mpg %>% 
  ggplot(aes(x = class, y = cty, fill = drv)) +
  geom_boxplot()
```

![](https://i.imgur.com/z6UCiat.png)

> Created on 2018-07-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by krlmlr** [comment]
The original issue can be solved with `reverse = TRUE`, maybe this should be the default (or inverted internally)?

``` r
library(tidyverse)
library(ggstance)
#> 
#> Attaching package: 'ggstance'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     geom_errorbarh, GeomErrorbarh

mpg %>%
  ggplot(aes(x = cty, y = class, fill = drv)) +
  geom_boxploth(position = position_dodge2v(padding = 0, reverse = TRUE))
```

![](https://i.imgur.com/MPle2vH.png)

<sup>Created on 2018-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by krlmlr** [comment]
(At least half of it -- it's easy enough to reverse the order of the vertical legend manually, but I still feel top-down is the most intuitive order, and _ggstance_ could make it easier for the user to achieve it.)

**Comment by krlmlr** [comment]
Thanks! So little code, so much bugfix!

The labels on the vertical axis are still reversed, though. This seems difficult to fix.

``` r
library(tidyverse)
library(ggstance)

mpg %>%
  ggplot(aes(x = cty, y = class, fill = drv)) +
  geom_boxploth()
```

![](https://i.imgur.com/YTcVNvs.png)

<sup>Created on 2019-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
We discussed it with @friep and @sowla and concluded the ordering of labels is right, because the bottom left corner is the origin.
