### ISSUE TITLE
differences between Geomerrorbarh in ggplot2 and ggstance

### ISSUE THREAD

**Issue by rpruim** [lionel-/ggstance#27]
Since both packages export `geom_errrorbarh()`, it would be nice if the documentation to clarify how they differ.  Looking through the code, I see that `ggplot2` uses `height` and `ggstance` uses `width` in the set up data.  Are there any other differences?

Is there any reason not to have these be identical?

**Comment by lionel-** [comment]
> Is there any reason not to have these be identical?

The change of direction, and consistency with other ggstance functions.

**Comment by lionel-** [comment]
Now supports `height` so it doesn't matter whether you attach ggplot2 before or after ggstance.
