### ISSUE TITLE
ggstance error with height argument (All height aesthetics in ggplot no longer work if ggstance is loaded)

### ISSUE THREAD

**Issue by lucyannewinder** [lionel-/ggstance#29]
As height is an argument in ggstance (for example in position_dodgev), this stops all height arguments in ggplot2. This means if say you want to adjust the tick mark height on the end of error bars (using geom_errorbarh) then the hight creates an error of : Warning: Ignoring unknown parameters: height. All height aesthics in ggplots do not work if ggstance is installed so other plots in the same script no longer work, not just in the same plot.

**Comment by lionel-** [comment]
I think this is just an issue with `geom_errorbarh()` right? Including a [reprex](https://github.com/tidyverse/reprex) in bug reports is always helpful by the way.
