### ISSUE TITLE
question, not issue

### ISSUE THREAD

**Issue by oeco28** [lionel-/ggstance#41]
I am using a modified version of the following command:

p + geom_facet(panel = "SNP", data = snp_data, geom = geom_point, 
               mapping=aes(x = pos, color = location), shape = '|')

in which I have added a fill by factor option:

p + geom_facet(panel = "vir_genes", data = vir_data4.2.2, geom = geom_point, mapping=aes(x = position, color=genes))

I would love to be able to specify a custom color palette. Let us say, I have 27 levels of the factor and I would like to pass the option viridis(27) to be used. 
  I have unsuccessfully tried different options. if you have any suggestion, that would be awesome!

thank you

**Comment by lionel-** [comment]
Sorry I don't have time to look into this. The package has been superseded by ggplot2 itself which now supports setting horizontal directions. In general, for user questions, I recommend posting on Community or StackOverflow.
