### ISSUE TITLE
Misleading error messages for missing aesthetics

### ISSUE THREAD

**Issue by Ax3man** [lionel-/ggstance#5]
For any of `geom_linerangeh`, `geom_pointrangeh`, `geom_crossbarh`, `geom_errorbarh`, the error for missing aesthetics still report the required aesthetics for the vertical versions.

`ggplot(mtcars) + geom_linerangeh()`

> `Error: geom_linerangeh requires the following missing aesthetics: x, ymin, ymax`

Even though it needs `y`, `xmin` and `xmax`.

This may be confusing for users that are changing an existing call to a horizontal one, where they already are supplying `x`, `ymin` and `ymax`.

**Comment by DoaneAS** [comment]
> This may be confusing for users that are changing an existing call to a horizontal one, where they already are supplying x, ymin and ymax.


Is definitely confusing, but appreciate  the answer above.

**Comment by lionel-** [comment]
This should now be fixed, thanks for the report

**Comment by Ax3man** [comment]
Great Lionel, you package is very useful indeed!
