### ISSUE TITLE
Feature request: CRAN release

### ISSUE THREAD

**Issue by huftis** [lionel-/ggstance#8]
`ggstance` seems like a very useful package, and it would be nice if it was available as a package on CRAN. It would make the package visible to a wider audience and make it more accessible (for example, some companies have policy of only allowing CRAN packages). So here’s a ‘feature request’ for a CRAN release. :)

**Comment by seth-1** [comment]
+1

**Comment by lionel-** [comment]
A CRAN release is planned but ggstance requires the dev version of ggplot to work correctly so we first have to wait for ggplot 2.2 to come out.

**Comment by lionel-** [comment]
Now on CRAN!
