### ISSUE TITLE
legend title NA induced by geom_boxploth

### ISSUE THREAD

**Issue by Pierre-Andre** [lionel-/ggstance#9]
data(diamonds)
geom_boxploth(data=diamonds,aes(y=-0.5,x=carat,fill=cut))+
geom_density(aes(x=carat,y=..density..)) +  facet_grid(cut~.)

does the job BUT (the order is reversed)

ggplot(data=diamonds) +
geom_density(aes(x=carat,y=..density..)) + 
geom_boxploth(data=diamonds,aes(y=-0.5,x=carat,fill=cut))+
facet_grid(cut~.)

produces a legend title "NA"

---

packageVersion("ggplot2")
[1] ‘2.1.0’
packageVersion("ggstance")
[1] ‘0.2.9000’
R.version.string
[1] "R version 3.3.1 (2016-06-21)"

**Comment by lionel-** [comment]
It looks like this is an upstream issue:

```r
ggplot(diamonds) +
  geom_density(aes(x = carat, y = ..density..)) +
  geom_boxplot(aes(x = -0.5, y = carat, fill = cut)) +
  facet_grid(. ~ cut)
```

Could you file there please?
